name: Harshitha
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Harshitha172000
  instagram:
  linkedin: harshitha-s-
# Build settings
theme: jekyll-theme-cayman
