name: Harshitha
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Harshitha172000
  instagram:
  linkedin: harshitha-s-
# Build settings
theme: jekyll-theme-cayman
